# Generated by Django 4.2.5 on 2025-09-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='razorpay_order_id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='razorpay_payment_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='brochure',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='brochures/covers/'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='page_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='brochures/pages/'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='page_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='brochures/pages/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='event_details',
            field=models.JSONField(blank=True, default=list, help_text='Detailed event selections with sub-options (MongoDB native)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='num_events',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='selected_events',
            field=models.JSONField(blank=True, default=list, help_text='List of event IDs selected by user (works perfectly with MongoDB)'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='brochures/pdfs/'),
        ),
        migrations.AlterModelTable(
            name='registration',
            table='registrations',
        ),
    ]
